name: 'SWM Github Actions Basic'

on: push

env:
  PRESET_VALUE: "This is PRESET value"


jobs:
  first_job:
    name: 'First Job'

    runs-on: ubuntu-latest

    env:
      JOB_LEVEL_1: "This value comes from the JOB level 1"
  

    steps:
    - name: 'Set output value'
      id: first
      shell: bash
      run: |
        var_1="This is the value 1 in the step 1"
        echo "::add-mask::$val_1"
        echo "::set-output name=first_value::$val_1"

    - name: 'Check output value'
      shell: pwsh
      run: |
        echo "${{ steps.first.outputs.first_value }}"
     