name: 'SWM Github Actions Basic'

on: 
  push:
    branches:
    - main
    tags:
    - 'v*'
  pull_request:
    branches:
      - main

jobs:
  first-job:
    name: 'First Job'

    if: github.event_name == 'push'

    strategy:
      matrix:
        os: ['ubuntu-latest','macos-latest','windows-latest ']

    runs-on: ${{ matrix.os }}

    steps:
    - name: 'Set output value'
      id: first
      shell: bash
      run: |
        var_1="This is the value: hello, world"

        echo "::set-output name=first_value::$val_1"

    - name: 'Check output value on ${{ matrix.os }}'
      if: matrix.os == 'ubuntu-latest'
      shell: pwsh
      run: |
        echo "${{ steps.first.outputs.first_value }}"
        