name: 'SWM Github Actions Basic'

on: push

jobs:
  first-job:
    name: 'First Job'

    strategy:
      matrix:
        os: ['ubuntu-latest','macos-latest','windows-latest ']

    runs-on: ${{ matrix.os }}

    steps:
    - name: 'Set output value'
      id: first
      shell: bash
      run: |
        var_1="This is the value 1 in the step 1"

        echo "::add-mask::$val_1"
        echo "::set-output name=first_value::$val_1"

    - name: 'Check output value on ${{ matrix.os }}'
      shell: pwsh
      run: |
        echo "${{ steps.first.outputs.first_value }}"
        echo "${{secrets.HELLO}}"