name: 'SWM Github Actions Basic'

on: push

jobs:
  first_job:
    name: 'First Job'

    runs-on: ubuntu-latest

    steps:
    - name: 'Set output value'
      id: first
      shell: bash
      run: |
        var_1="This is the value 1 in the step 1"

        echo "::add-mask::$val_1"
        echo "::set-output name=first_value::$val_1"

    - name: 'Check output value'
      shell: pwsh
      run: |
        echo "${{ steps.first.outputs.first_value }}"
        echo "${{secrets.HELLO}}"