name: 'SWM Github Actions Basic'

on: ['push', 'pull_request']

jobs:
  first-job:
    name: 'First Job'

    if: github.event_name == 'pull_request'

    strategy:
      matrix:
        os: ['ubuntu-latest','macos-latest','windows-latest ']
        message: ['HELLO WORLD','LOREM IPSUM']

    runs-on: ${{ matrix.os }}

    steps:
    - name: 'Set output value'
      id: first
      shell: bash
      run: |
        var_1="This is the value: ${{ matrix.message }}"

        echo "::set-output name=first_value::$val_1"

    - name: 'Check output value on ${{ matrix.os }}'
      shell: pwsh
      run: |
        echo "${{ steps.first.outputs.first_value }}"